name: Manabata
description: An app to request for blood donation to users in similar area.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
#  geolocation: ^10.1.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^3.0.0

flutter:
  assets:
      - assets/logo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"